Make sure sys/prctl.h is included only on Linux
on FreeBSD such an include file does not exist:
./src/base/Thread.h:29:10: fatal error: 'sys/prctl.h' file not found